import { ModuleDefinition } from "../types/modules";
import { DiscordRole, DiscordChannel, DashboardAuthUser } from "../types/discord";
import { AuditLogEntry, BotStatusResponse } from "../types/audit";

export const MOCK_DISCORD_ROLES: DiscordRole[] = [
  { id: "743423786275307542", name: "Owner", color: 0xe91e63, position: 50, permissions: "8" },
  { id: "738193447017513002", name: "[VRP] Management", color: 0x9b59b6, position: 48, permissions: "8" },
  { id: "1513635168353779915", name: "Head of Staff", color: 0x3498db, position: 46, permissions: "8" },
  { id: "1251959011872342057", name: "Head Administrator", color: 0x2ecc71, position: 44, permissions: "8" },
  { id: "733090996660863056", name: "Senior Administrator", color: 0x1abc9c, position: 42, permissions: "8" },
  { id: "733091115577901158", name: "Administrator", color: 0xe67e22, position: 40, permissions: "8" },
  { id: "743422836223246366", name: "Staff Team", color: 0xf1c40f, position: 35, permissions: "0" },
  { id: "733091376832708689", name: "Moderator", color: 0x34495e, position: 30, permissions: "0" },
  { id: "733091380540473384", name: "Support Staff", color: 0x95a5a6, position: 25, permissions: "0" },
  { id: "1546696583976980541", name: "Staff LOA", color: 0x7289da, position: 20, permissions: "0" },
  { id: "1547049587993223229", name: "LOA - Support", color: 0x99aab5, position: 19, permissions: "0" },
  { id: "1241050651677556806", name: "Whitelist Approved", color: 0x57f287, position: 15, permissions: "0" },
  { id: "1371677888964726818", name: "Keyboard Warrior", color: 0xeb459e, position: 10, permissions: "0" },
  { id: "735479005561618452", name: "Gif", color: 0xfee75c, position: 8, permissions: "0" },
  { id: "733384365513506856", name: "Member", color: 0xffffff, position: 5, permissions: "0" },
];

export const MOCK_DISCORD_CHANNELS: DiscordChannel[] = [
  { id: "1546281163247722516", name: "loa-center", type: 0 },
  { id: "1546698584613715998", name: "loa-audit-logs", type: 0 },
  { id: "1289638609535766631", name: "refund-center", type: 0 },
  { id: "1249517344099668078", name: "punishment-logs", type: 0 },
  { id: "1446287220389712024", name: "suggestions", type: 0 },
  { id: "1403073578034921512", name: "suggestions-testing", type: 0 },
  { id: "1220039518279827528", name: "support-chat", type: 0 },
  { id: "1215416531257794621", name: "moderator-chat", type: 0 },
  { id: "1252979165192261642", name: "admin-chat", type: 0 },
  { id: "1240000000000000001", name: "referral-submissions", type: 0 },
  { id: "1240000000000000002", name: "referral-logs", type: 0 },
  { id: "1240000000000000003", name: "welcome-and-rules", type: 0 },
];

export const MOCK_CURRENT_USER: DashboardAuthUser = {
  id: "150580708144840704",
  username: "damon",
  displayName: "Damon",
  avatarUrl: "https://r2.fivemanage.com/image/4sIiNuE1Vmvn.png",
  roles: ["743423786275307542", "738193447017513002"],
  roleName: "Owner / Bot Superadmin",
  accessLevel: "owner",
  permissions: {
    canManageAll: true,
    canManageModules: true,
    canViewAudit: true,
    canEditSystem: true,
  },
};

export const MOCK_BOT_STATUS: BotStatusResponse = {
  status: "online",
  botName: "DamoBot",
  version: "v0.9.90-beta",
  guildId: "730015674348601384",
  guildName: "Vital RP",
  uptime: "99.98%",
  activeModulesCount: 8,
  totalModulesCount: 9,
  d1Databases: [
    { name: "damo-bot-punishments", binding: "PUNISHMENT_DB", connected: true },
    { name: "damo-bot-refunds", binding: "REFUND_DB", connected: true },
  ],
  durableObjects: [
    { name: "StaffLoaDO", class: "StaffLoaDO", status: "active" },
    { name: "StickyBotDO", class: "StickyBotDO", status: "active" },
    { name: "SuggestionsDO", class: "SuggestionsDO", status: "active" },
    { name: "PunishmentSequenceDO", class: "PunishmentSequenceDO", status: "active" },
  ],
  environment: {
    valid: true,
    errors: [],
    warnings: [],
  },
  lastConfigUpdate: new Date().toISOString(),
};

export const MOCK_MODULE_DEFINITIONS: ModuleDefinition[] = [
  {
    id: "loa",
    name: "Staff LOA Center",
    description: "Manage Staff Leave of Absence (LOA), early returns, nickname tracking, and role snapshots.",
    category: "staff",
    iconName: "CalendarOff",
    staffOnly: true,
    enabled: true,
    version: "v1.2",
    configurable: true,
    stats: [
      { label: "Active LOAs", value: "3" },
      { label: "Pending Returns", value: "1" },
    ],
    settingsSchema: [
      {
        key: "enabled",
        label: "Module Enabled",
        description: "Master switch for the Staff LOA Center.",
        type: "boolean",
        defaultValue: true,
        danger: true,
        requiresConfirm: true,
      },
      {
        key: "channels.center",
        label: "LOA Center Channel",
        description: "Channel where the interactive LOA panel is posted.",
        type: "discord_channel",
        defaultValue: "1546281163247722516",
      },
      {
        key: "channels.logs",
        label: "LOA Audit Logs Channel",
        description: "Private audit log channel where LOA requests, approvals, and returns are posted.",
        type: "discord_channel",
        defaultValue: "1546698584613715998",
      },
      {
        key: "roles.staffLoa",
        label: "Staff LOA Role",
        description: "Role assigned to staff while on leave.",
        type: "discord_role",
        defaultValue: "1546696583976980541",
      },
      {
        key: "roles.allowed",
        label: "Allowed Request Roles",
        description: "Discord roles permitted to request their own LOA.",
        type: "discord_roles",
        defaultValue: [
          "743422836223246366",
          "743423786275307542",
          "733091115577901158",
          "1513635168353779915",
          "738193447017513002",
          "733090996660863056",
          "1251959011872342057",
          "733091376832708689",
          "733091380540473384",
        ],
      },
      {
        key: "roles.managers",
        label: "LOA Managers",
        description: "Roles permitted to review, approve, deny, or cancel any staff member's LOA.",
        type: "discord_roles",
        defaultValue: [
          "743423786275307542",
          "738193447017513002",
          "1513635168353779915",
          "1251959011872342057",
          "733090996660863056",
          "733091115577901158",
        ],
      },
      {
        key: "settings.minimumDays",
        label: "Minimum LOA Days",
        description: "Minimum duration allowable in a single LOA request.",
        type: "number",
        defaultValue: 1,
      },
      {
        key: "settings.maximumDays",
        label: "Maximum LOA Days",
        description: "Maximum duration allowable in a single LOA request.",
        type: "number",
        defaultValue: 30,
      },
      {
        key: "settings.allowEarlyEnd",
        label: "Allow Early Return",
        description: "Whether staff members can return early and end their own LOA.",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "settings.allowEdit",
        label: "Allow Date/Reason Edits",
        description: "Whether staff can modify their active LOA end date or reason.",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "settings.autoRestoreOnExpiry",
        label: "Auto-Restore on Expiry",
        description: "If disabled, expired LOAs stay active as OVERDUE until ended by staff.",
        type: "boolean",
        defaultValue: false,
      },
    ],
  },
  {
    id: "punishments",
    name: "Staff Punishment Center",
    description: "Punishment logging (bans, warns) with sequential IDs, searchable logs, and Google Sheets backup.",
    category: "staff",
    iconName: "ShieldAlert",
    staffOnly: true,
    enabled: true,
    version: "v1.1",
    configurable: true,
    stats: [
      { label: "Cases Logged", value: "1,248" },
      { label: "D1 Database", value: "Healthy" },
    ],
    settingsSchema: [
      {
        key: "channels.logs",
        label: "Punishment Log Channel",
        description: "Channel where punishment cases are announced.",
        type: "discord_channel",
        defaultValue: "1249517344099668078",
      },
      {
        key: "sheets.sheetId",
        label: "Google Sheets Backup ID",
        description: "Spreadsheet ID for historical punishment backup.",
        type: "string",
        defaultValue: "1CxMo8nLs_Ln6siVPOk4oqSwjgQr3E0GzKdZZHPVbvm0",
      },
      {
        key: "sheets.sheetTab",
        label: "Sheet Tab Name",
        description: "Target tab inside Google Sheets.",
        type: "string",
        defaultValue: "Punishment Logs",
      },
    ],
  },
  {
    id: "refunds",
    name: "Staff Refund Center",
    description: "Player refund management across Vitcoin, Cash, S-Coin, and custom categories.",
    category: "staff",
    iconName: "Receipt",
    staffOnly: true,
    enabled: true,
    version: "v1.3",
    configurable: true,
    stats: [
      { label: "Open Requests", value: "4" },
      { label: "Completed", value: "312" },
    ],
    settingsSchema: [
      {
        key: "enabled",
        label: "Module Enabled",
        description: "Master switch for the Refund Center.",
        type: "boolean",
        defaultValue: true,
        danger: true,
        requiresConfirm: true,
      },
      {
        key: "channels.center",
        label: "Refund Center Channel",
        description: "Channel for the Refund Center panel.",
        type: "discord_channel",
        defaultValue: "1289638609535766631",
      },
      {
        key: "settings.maxOpenRequestsPerUser",
        label: "Max Open Requests Per User",
        description: "Maximum active refund requests a player can have simultaneously.",
        type: "number",
        defaultValue: 1,
      },
      {
        key: "categories",
        label: "Refund Categories",
        description: "Manage dynamic refund categories (Vitcoin, Cash, S-Coin, etc.).",
        type: "categories_refund",
        defaultValue: [
          { id: "Vitcoin", label: "Vitcoin", emoji: "🪙", description: "In-game Vitcoin currency refund", enabled: true },
          { id: "Cash", label: "Cash", emoji: "💵", description: "In-game cash currency refund", enabled: true },
          { id: "S-Coin", label: "S-Coin", emoji: "💎", description: "Special currency refund", enabled: true },
          { id: "Other", label: "Other", emoji: "📦", description: "Custom item, vehicle, or weapon refund", enabled: true },
        ],
      },
    ],
  },
  {
    id: "suggestions",
    name: "Community Suggestions",
    description: "Vital RP suggestions with upvoting/downvoting, cooldowns, and sticky prompt.",
    category: "community",
    iconName: "Lightbulb",
    staffOnly: false,
    enabled: true,
    version: "v2.0",
    configurable: true,
    stats: [
      { label: "Suggestions", value: "482" },
      { label: "Top Score", value: "+94" },
    ],
    settingsSchema: [
      {
        key: "channels.activeChannelId",
        label: "Suggestions Channel",
        description: "Target channel where community suggestions and votes are posted.",
        type: "discord_channel",
        defaultValue: "1446287220389712024",
      },
      {
        key: "cooldownSeconds",
        label: "Per-User Cooldown (seconds)",
        description: "Cooldown duration between player submissions.",
        type: "number",
        defaultValue: 300,
      },
      {
        key: "features.anonymousEnabled",
        label: "Allow Anonymous Submissions",
        description: "Allow players to submit suggestions without displaying their username.",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "features.votingEnabled",
        label: "Enable Voting",
        description: "Allow server members to upvote or downvote suggestions.",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "features.imageUploadEnabled",
        label: "Allow Image Attachments",
        description: "Allow players to supply image URLs for visual mockups.",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "categories",
        label: "Suggestion Categories",
        description: "Categories available for community suggestions.",
        type: "categories_suggestion",
        defaultValue: [
          { id: "scripts", label: "Scripts", emoji: "📜", description: "Server scripts, jobs, and gameplay mechanics", enabled: true },
          { id: "rule_changes", label: "Rule Changes", emoji: "⚖️", description: "Server rules and policy updates", enabled: true },
          { id: "new_features", label: "New Features", emoji: "💡", description: "Brand new gameplay features", enabled: true },
          { id: "server_changes", label: "Server Changes", emoji: "⚙️", description: "Vehicle handling or server settings", enabled: true },
          { id: "qol", label: "Quality of Life", emoji: "✨", description: "Small improvements", enabled: true },
          { id: "other", label: "Other", emoji: "📌", description: "General proposals", enabled: true },
        ],
      },
    ],
  },
  {
    id: "referrals",
    name: "Player Referral System",
    description: "Track player recruitment, anti-duplicate verification, and Google Sheets tracker.",
    category: "community",
    iconName: "Users",
    staffOnly: false,
    enabled: true,
    version: "v1.0",
    configurable: true,
    stats: [
      { label: "Total Referrals", value: "246" },
      { label: "Sheet Sync", value: "Active" },
    ],
    settingsSchema: [
      {
        key: "enabled",
        label: "Module Enabled",
        description: "Master switch for player referral submissions.",
        type: "boolean",
        defaultValue: true,
      },
      {
        key: "channels.referrals",
        label: "Allowed Channel",
        description: "Channel where /referral can be executed (leave empty for server-wide).",
        type: "discord_channel",
        defaultValue: "",
      },
      {
        key: "requirements.accountAgeDays",
        label: "Min Account Age (Days)",
        description: "Minimum account age required for reward eligibility.",
        type: "number",
        defaultValue: 30,
      },
      {
        key: "requirements.minimumPlaytimeHours",
        label: "Min Playtime (Hours)",
        description: "Minimum in-game playtime hours required.",
        type: "number",
        defaultValue: 10,
      },
      {
        key: "settings.preventDuplicateReferrals",
        label: "Prevent Duplicate Referrals",
        description: "Prevent a user from being referred multiple times.",
        type: "boolean",
        defaultValue: true,
      },
    ],
  },
  {
    id: "reminders",
    name: "Ticket Reminders",
    description: "Support ticket reminders with scheduled cron triggers inside ticket threads.",
    category: "staff",
    iconName: "Clock",
    staffOnly: true,
    enabled: false,
    version: "v1.0",
    configurable: true,
    stats: [
      { label: "Feature Status", value: "Disabled in wrangler" },
      { label: "Cron Cycle", value: "Every 1m" },
    ],
    settingsSchema: [
      {
        key: "enabled",
        label: "Module Enabled",
        description: "Master switch for Ticket Reminders cron and /remind command.",
        type: "boolean",
        defaultValue: false,
        danger: true,
      },
      {
        key: "channelId",
        label: "Ticket Channel",
        description: "Support channel where ticket reminders operate.",
        type: "discord_channel",
        defaultValue: "1220039518279827528",
      },
    ],
  },
  {
    id: "stickies",
    name: "Sticky Channel Messages",
    description: "Keep important notices and ActionRow buttons anchored to the bottom of channels.",
    category: "utility",
    iconName: "Pin",
    staffOnly: true,
    enabled: true,
    version: "v1.2",
    configurable: true,
    stats: [
      { label: "Active Stickies", value: "3" },
      { label: "DO Polling", value: "1m" },
    ],
    settingsSchema: [
      {
        key: "defaultButton",
        label: "Default Interactive Button",
        description: "Standard action button to attach to new stickies.",
        type: "select",
        options: [
          { label: "None", value: "none" },
          { label: "⚖️ Punishment Center", value: "punishment_center" },
          { label: "💰 Refund Center", value: "refund_center" },
          { label: "Both Centers", value: "both" },
        ],
        defaultValue: "none",
      },
    ],
  },
  {
    id: "admin-chat",
    name: "Admin Chat Mentions",
    description: "Sarcastic, humorous, and unhinged response bank when admins mention DamoBot.",
    category: "utility",
    iconName: "MessageSquare",
    staffOnly: true,
    enabled: true,
    version: "v1.0",
    configurable: true,
    stats: [
      { label: "Responses in Bank", value: "56" },
      { label: "Channel", value: "admin-chat" },
    ],
    settingsSchema: [
      {
        key: "channelId",
        label: "Admin Chat Channel",
        description: "Channel ID for admin chat integrations.",
        type: "discord_channel",
        defaultValue: "1252979165192261642",
      },
      {
        key: "responses",
        label: "Response Quotes",
        description: "List of random sarcastic responses sent upon mention.",
        type: "string_array",
        defaultValue: [
          "what",
          "I'm busy",
          "who summoned me",
          "I was sleeping",
          "this better be important",
          "womp womp",
          "skill issue",
          "have you tried turning it off and back on",
          "Damon made me do this",
        ],
      },
    ],
  },
  {
    id: "overview",
    name: "Bot Status & Overview",
    description: "Bot health checks, /ping responsiveness, and interactive /damobot capability showcase.",
    category: "utility",
    iconName: "Activity",
    staffOnly: false,
    enabled: true,
    version: "v1.0",
    configurable: false,
    stats: [
      { label: "Commands", value: "/ping, /damobot" },
      { label: "Latency", value: "14ms" },
    ],
    settingsSchema: [],
  },
];

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud-001",
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    userId: "150580708144840704",
    userName: "Damon",
    moduleId: "loa",
    moduleName: "Staff LOA Center",
    action: "update_setting",
    key: "settings.maximumDays",
    oldValue: 21,
    newValue: 30,
  },
  {
    id: "aud-002",
    timestamp: new Date(Date.now() - 1000 * 60 * 64).toISOString(),
    userId: "150580708144840704",
    userName: "Damon",
    moduleId: "suggestions",
    moduleName: "Community Suggestions",
    action: "update_setting",
    key: "cooldownSeconds",
    oldValue: 600,
    newValue: 300,
  },
  {
    id: "aud-003",
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    userId: "150580708144840704",
    userName: "Damon",
    moduleId: "refunds",
    moduleName: "Staff Refund Center",
    action: "update_setting",
    key: "categories",
    oldValue: "4 categories",
    newValue: "Updated emoji for S-Coin",
  },
];
